### ISSUE TITLE
Cannot import name 'Polygon' from 'shapely'

### ISSUE THREAD

**Issue by raffaelemancuso** [ColinMoldenhauer/FastPyNUTS#3]
I'm just trying it and it errors out

```
➜  python
Python 3.12.2 (main, Apr 11 2024, 09:19:40) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastpynuts import NUTSfinder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raffaele/.pyenv/versions/3.12.2/lib/python3.12/site-packages/fastpynuts/__init__.py", line 5, in <module>
    from .fastpynuts import NUTSregion, NUTSfinder
  File "/home/raffaele/.pyenv/versions/3.12.2/lib/python3.12/site-packages/fastpynuts/fastpynuts.py", line 11, in <module>
    from shapely import Polygon, intersects, intersects_xy, is_geometry
ImportError: cannot import name 'Polygon' from 'shapely' (/home/raffaele/.pyenv/versions/3.12.2/lib/python3.12/site-packages/shapely/__init__.py)
```

**Comment by ColinMoldenhauer** [comment]
Might be an issue with your version of `shapely`, I think the geometry objects are directly importable in newer versions. Let me know if updating your version helps

**Comment by raffaelemancuso** [comment]
Indeed https://shapely.readthedocs.io/en/stable/release/2.x.html#geometry-subclasses-are-now-available-in-the-top-level-namespace

**Comment by raffaelemancuso** [comment]
I submitted a PR that enforce2.0 as minimum shapeley version
