### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by raffaelemancuso** [ColinMoldenhauer/FastPyNUTS#6]
I'm now getting this error:

```
>>> nf = NUTSfinder.from_web(scale=1, year=2021, epsg=4326)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/MYPATH/FastPyNUTS/fastpynuts/fastpynuts.py", line 135, in from_web
    return cls(download_NUTS(datadir, scale=scale, year=year, epsg=epsg), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MYPATH/FastPyNUTS/fastpynuts/fastpynuts.py", line 102, in __init__
    self.regions = self._load_regions()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/MYPATH/FastPyNUTS/fastpynuts/fastpynuts.py", line 206, in _load_regions
    regions_filtered = self._filter_regions(fc)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MYPATH/FastPyNUTS/fastpynuts/fastpynuts.py", line 199, in _filter_regions
    regions = [NUTSregion(feature, self.buffer) for feature in filtered]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MYPATH/FastPyNUTS/fastpynuts/fastpynuts.py", line 41, in __init__
    assert feature["id"] == feature["properties"]["NUTS_ID"]
           ~~~~~~~^^^^^^
KeyError: 'id'
```

**Comment by ColinMoldenhauer** [comment]
From the pull request I figure you are using the new 2024 dataset? Can you post a snippet from the 2024 dataset and one of the older ones?

**Comment by ColinMoldenhauer** [comment]
Huh, they seem to have changed the dataset format. There used to be a key `id`...
Will change :)


```json
snippet from the previous dataset:
{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "MultiPolygon",
				"coordinates": ...
				},
			"properties": {
				"NUTS_ID": "FR",
				"LEVL_CODE": 0,
				"CNTR_CODE": "FR",
				"NAME_LATN": "France",
				"NUTS_NAME": "France",
				"MOUNT_TYPE": 0,
				"URBN_TYPE": 0,
				"COAST_TYPE": 0,
				"FID": "FR"
			},
			"id": "FR"
		},
                ...
}

compared to the new format
{
	"type": "FeatureCollection",
	"name": "NUTS_RG_20M_2021_4326.geojson",
	"features": [
		{
			"type": "Feature",
			"properties": {
				"NUTS_ID": "FR",
				"LEVL_CODE": 0,
				"CNTR_CODE": "FR",
				"NAME_LATN": "France",
				"NUTS_NAME": "France",
				"MOUNT_TYPE": 0,
				"URBN_TYPE": 0,
				"COAST_TYPE": 0
			},
			"geometry": ...,
		},
                ...
}
```
